### ISSUE TITLE
Assessing the Need for User Join/Leave Event Detection in rocketchat-async

### ISSUE THREAD

**Issue by kato-mahiro** [hynek-urban/rocketchat-async#10]
Hello there,

I've been using the rocketchat-async library for our project (https://github.com/Dot-labo/rocketchat-ai-assistant), and I've come across the need for a feature that seems to be missing at the moment. Specifically, I'm interested in detecting when users join or leave into channels.

Would it be within the scope of this library to implement such a feature? I'm envisioning a method, perhaps something like rc.detect_user_events(), that can capture events of users joining or leaving channels when they occur.

I plan on implementing these changes for this and thought it might be a valuable addition to the library. Could this be something the community would find useful, and is it worth contributing to the rocketchat-async project?

Thank you for considering my suggestion.

Best regards,

**Comment by hynek-urban** [comment]
Totally, it would be both in scope and useful :) I'll take a look at the PR you set up.

**Comment by hynek-urban** [comment]
@kato-mahiro As discussed in https://github.com/hynek-urban/rocketchat-async/pull/11, there is the new `subscribe_to_channel_changes_raw()` method. Let me know if it doesn't address the use case you're mentioning! (Or if you can come up with something more elegant :) )
